const UPDATE_COUNTRIES = "UPDATE_COUNTRIES";
const UPDATE_CITIES = "UPDATE_CITIES";
const UPDATE_TRENDING_MOVIES = "UPDATE_TRENDING_MOVIES";
const UPDATE_TRENDING_TV = "UPDATE_TRENDING_TV";
const UPDATE_PRIME_SHOW = "UPDATE_PRIME_SHOW";
const UPDATE_REGIONAL_MOVIES = "UPDATE_REGIONAL_MOVIES";
const UPDATE_PRIME_SHOW_EPISODES = "UPDATE_PRIME_SHOW_EPISODES";
const API_KEY = "961ed7aca229e9e5404c79983c87a777";
const REQUEST_GET = "GET";
const PRIME_SHOW_ID = 1100;
const UPDATE_IS_HOME = "UPDATE_IS_HOME";
const UPDATE_MEDIA = "UPDATE_MEDIA";
const UPDATE_MEDIA_SEASONS = "UPDATE_MEDIA_SEASONS";
const BASE_TV_URL = `https://api.themoviedb.org/3/tv/`;
const UPDATE_COMPLETE_MEDIA = "UPDATE_COMPLETE_MEDIA";
const UPDATE_REGIONAL_HI_MOVIES = "UPDATE_REGIONAL_HI_MOVIES";
const UPDATE_ADULT_MOVIES = "UPDATE_ADULT_MOVIES";
export {
  UPDATE_COUNTRIES,
  UPDATE_CITIES,
  API_KEY,
  REQUEST_GET,
  UPDATE_TRENDING_MOVIES,
  UPDATE_TRENDING_TV,
  UPDATE_PRIME_SHOW,
  UPDATE_REGIONAL_MOVIES,
  UPDATE_PRIME_SHOW_EPISODES,
  PRIME_SHOW_ID,
  UPDATE_IS_HOME,
  UPDATE_MEDIA,
  UPDATE_MEDIA_SEASONS,
  BASE_TV_URL,
  UPDATE_COMPLETE_MEDIA,
  UPDATE_REGIONAL_HI_MOVIES,
  UPDATE_ADULT_MOVIES
};
