const UPDATE_COUNTRIES = "UPDATE_COUNTRIES";
const UPDATE_CITIES = "UPDATE_CITIES";
const UPDATE_TRENDING_MOVIES = "UPDATE_TRENDING_MOVIES";
const UPDATE_TRENDING_TV = "UPDATE_TRENDING_TV";
const UPDATE_PRIME_SHOW = "UPDATE_PRIME_SHOW";
const UPDATE_REGIONAL_MOVIES = "UPDATE_REGIONAL_MOVIES";
const API_KEY = "961ed7aca229e9e5404c79983c87a777";
const REQUEST_GET = "GET";

export {
  UPDATE_COUNTRIES,
  UPDATE_CITIES,
  API_KEY,
  REQUEST_GET,
  UPDATE_TRENDING_MOVIES,
  UPDATE_TRENDING_TV,
  UPDATE_PRIME_SHOW,
  UPDATE_REGIONAL_MOVIES
};
